yuido_file_manager_upload:
    path:     /upload/{entityName}/{entityId}
    defaults: { _controller: YuidoFileManagerBundle:FileManager:upload }
    requirements:
      entity_id: \d+

yuido_file_manager_show_uploaded_file:
    path:     /show_uploaded_file/{id}
    defaults: { _controller: YuidoFileManagerBundle:FileManager:showUploadedFile }

yuido_file_manager_test:
    path:     /test
    defaults: { _controller: YuidoFileManagerBundle:FileManager:test }