yuido_file_manager_get:
    path:     /get/{entityName}/{entityId}
    defaults: { _controller: YuidoFileManagerBundle:FileManager:get }
    requirements:
      entityId: \d+

yuido_file_manager_delete:
    path:     /delete/{entityName}/{entityId}/{fileId}
    defaults: { _controller: YuidoFileManagerBundle:FileManager:delete, fileId: '' }
    requirements:
      entityId: \d+

yuido_file_manager_upload:
    path:     /upload/{entityName}/{entityId}
    defaults: { _controller: YuidoFileManagerBundle:FileManager:upload }
    requirements:
      fileId: \d+
      entityId: \d+

yuido_file_manager_show_uploaded_file:
    path:     /show_uploaded_file/{id}
    defaults: { _controller: YuidoFileManagerBundle:FileManager:showUploadedFile }

yuido_file_manager_test:
    path:     /test
    defaults: { _controller: YuidoFileManagerBundle:FileManager:test }