<?php

namespace Yuido\GestorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormacionUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormacionUserRepository extends EntityRepository
{
}
