<?php

namespace Yuido\GestorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MasterClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MasterClassRepository extends EntityRepository
{
}
